services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: arbitrage-graphs-frontend
    container_name: arbitrage-graphs-frontend-container
    ports:
      - "3000:80"
      - "443:443"
    volumes:
      - .:/app
      - /app/node_modules
